version: '3'
services:
  mockit-routes:
    image: 'mockit-routes'
    build: 'mockit-routes'
    ports:
      - 10030:3000
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - ./configuration/routes.json:/usr/src/mockit-routes/configuration/routes.json
  mockit-server:
    image: 'mockit-server'
    build: 'server'
    ports:
      - 10040:4000
    volumes:
      - ./configuration/routes.json:/usr/src/mockit-server/configuration/routes.json
  mockit-client:
    image: 'mockit-client'
    build: 'client'
    ports:
      - 10050:3000
    environment:
      - REACT_APP_MOCKIT_SERVER_URL=http://localhost:10030
      - REACT_APP_MOCKIT_API_URL=http://localhost:10040
    volumes:
      - ./configuration/routes.json:/usr/src/mockit-client/src/config/routes.json
